### ISSUE TITLE
[Bug]: [1.18.2] Crash on Startup

### ISSUE THREAD

**Issue by pewblaze** [ThatGravyBoat/Duckling#1]
### Bug Description

I loaded the mod today, but i get a crash on startup. Without the mod it starts without any issues.

In the log is a crash report with playdate? It works fine without this mod, so im not sure where to post this. ^^"
Help would be aweomse how to fix it :)

### How to Reproduce?

1. Start the game 

### Version

duckling-1.0.0-fabric

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

### Logs or additional context

Crash log: https://pastebin.com/C8hn23sF
Log: https://pastebin.com/KcBzXHFS

**Comment by ThatGravyBoat** [comment]
Ill push a fix in a bit if that thing I just changed fixed this

**Comment by ThatGravyBoat** [comment]
Ok fixed, you can update to fabric version 1.0.1 and it will work https://www.curseforge.com/minecraft/mc-mods/duckling/files/all
