### ISSUE TITLE
[Bug]: ducks on leads have an extra lead coming out of them

### ISSUE THREAD

**Issue by caeserlettuce** [ThatGravyBoat/Duckling#15]
### Bug Description

when a duck is on a lead, there is a second rendered lead that seems to rotate with the body, that just kind of, exists?
![2022-07-19_18 19 05](https://user-images.githubusercontent.com/84699501/179875209-48a67501-0945-4921-8d88-849111c118a7.png)

Here's a recording of it:
https://youtu.be/lSbrJGX5PB

I'm using 1.18.2 forge 40.1.60 with duckling mod 1.0.5

### How to Reproduce?

attatch a lead to a duck

### Expected Behavior

there to be a singular lead

### Version

1.0.5

### Mod Loader Version

1.18.2 - 40.1.60

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Fixed in 1.0.6
