### ISSUE TITLE
[Bug]: duckling mod not loading

### ISSUE THREAD

**Issue by sarloyt** [ThatGravyBoat/Duckling#16]
### Bug Description

the mod fails to load when opening the gam
[crash-2022-07-21_16.15.27-fml.txt](https://github.com/ThatGravyBoat/Duckling/files/9162873/crash-2022-07-21_16.15.27-fml.txt)
e

### How to Reproduce?

1. open the game launcher
2. start the game

### Expected Behavior

game opens normaly

### Version

1.0.5

### Mod Loader Version

1.18.2 - 40.1.68

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
You do not have geckolib installed.

**Comment by sarloyt** [comment]
i have gekolib installed, that was the first thing i checked

**Comment by ThatGravyBoat** [comment]
well thats what the crash log says so make sure you have the correct geckolib installed.

**Comment by sarloyt** [comment]
i just noticed i installed the fabric version instead of the forge one, thanks for the help
