### ISSUE TITLE
[Bug]: Load Error

### ISSUE THREAD

**Issue by CarlossPB** [ThatGravyBoat/Duckling#17]
### Bug Description

Duckling fails logging into minecraft

### How to Reproduce?

After entering into Minecraft Duckling fails to load correctly , I have downloaded geckolib in it´s last version as duckling and it´s fails

### Expected Behavior

Enter Minecraft without problems

### Version

2.0.3

### Mod Loader Version

1.19-41.0.100

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
as of right now duckling only works on forge 41.0.63 and below.

**Comment by CarlossPB** [comment]
Ok. thks!
