### ISSUE TITLE
[Bug]: Quakclings doesnt appear

### ISSUE THREAD

**Issue by boohuwz** [ThatGravyBoat/Duckling#19]
### Bug Description

(I am using a translator)
the quacklings do not appear in my world, I checked five vanilla swamps and I did not find a single quackling, instead in the river biomes I did find ducks

what's the problem with the quacklings?

![Screenshot_8](https://user-images.githubusercontent.com/110626561/182914150-57c35ae0-2445-408e-ac98-f54dc8aaa46b.png)

![Screenshot_9](https://user-images.githubusercontent.com/110626561/182914197-2772ad07-aaad-494d-b845-634839a294da.png)

### How to Reproduce?

Checking the biomes and that quakclings do not appear

### Expected Behavior

what if quaklings appear

### Version

1.0.5

### Mod Loader Version

1.18.2-forge-40.1.68

### Mod Loader

Forge

### Logs or additional context

mods that i use:

![1](https://user-images.githubusercontent.com/110626561/182914601-465dc76a-bf99-4dd0-b128-c66407cc88e8.png)
![2](https://user-images.githubusercontent.com/110626561/182914627-462b5550-e81e-4ef2-8741-268993cfcdac.png)
![Screenshot_10](https://user-images.githubusercontent.com/110626561/182914636-4dd4d990-3bb0-4fee-a68b-e3ef6266c7a3.png)

**Comment by ThatGravyBoat** [comment]
Ive changed how they spawn a bit in 1.0.6 so you should see them spawn. Do note they are rare and I can confirm with just the mod itself they do spawn as I test spawning and do in-world tests to check if spawning and such works.
