### ISSUE TITLE
[Bug]: Throwing Duck Eggs at Wall can push ducks and make them suffocate

### ISSUE THREAD

**Issue by SafeOfArsenal** [ThatGravyBoat/Duckling#2]
### Bug Description

When spamming eggs at a wall it can push a hatched duck into a block and suffocate it

### Expected Behavior

that they do not get pushed in the wall and just like fall down

### Version

1.0.3

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Fixed in 1.0.5
