### ISSUE TITLE
[Bug]: Instant disconnect on servers when near a Duck.

### ISSUE THREAD

**Issue by Gbergz** [ThatGravyBoat/Duckling#22]
### Bug Description

When near a duck on servers it causes an instant disconnect, placing one with spawn eggs also instant disconnect.
You can't rejoin to due the crash, only if the duck is dead.

### How to Reproduce?

1. Go near a duck / place it with a spawn egg.
2. Instant Disconnect.
Profit.

### Expected Behavior

That you're not disconnected when near a duck.

### Version

1.0.6-Fabric

### Mod Loader Version

1.18.2 - 0.14.9

### Mod Loader

Fabric

### Logs or additional context

Logs: https://gist.github.com/Gbergz/6cedb6c285348bf358c31eb6b61f4351

Reproducable:
Modpack is [Limitless: Refabricated](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-refabricated), you can download it start a server, place a duck with spawn egg. Instant disconnect.

**Comment by ThatGravyBoat** [comment]
please provide the full log.

**Comment by Gbergz** [comment]
https://gist.github.com/Gbergz/9b33231226bc006a31f0df75264e98f1

**Comment by Gbergz** [comment]
It is though, but oh well.
Maybe a cross mod issue, no idea.

**Comment by ThatGravyBoat** [comment]
I just spawned literally a couple hundred ducks and not a single crash, the bug error does show up so that will get fixed but it does not crash.

**Comment by Gbergz** [comment]
Interesting, maybe the disconnect issue on a server is just on my end then.

**Comment by ThatGravyBoat** [comment]
The error has been fixed in 1.0.7
