### ISSUE TITLE
[Bug]: If done correctly you can throw a egg through a glass pane

### ISSUE THREAD

**Issue by SafeOfArsenal** [ThatGravyBoat/Duckling#26]
### Bug Description

its in the title

### How to Reproduce?

start throwing eggs at the glass pane until you find the correct angle then the duck spawns behind the pane

### Expected Behavior

You can't throw it through the glass pane

### Version

2.0.7

### Mod Loader Version

1.19.2 Fabric

### Mod Loader

Fabric

### Logs or additional context

r

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
The logic behind the throwing code is a 1:1 to vanilla so this would also be a vanilla bug and I would like to keep it 1:1 to not have it be annoying to change/port in the future.

**Comment by ThatGravyBoat** [comment]
this is just a flaw in the game's design and causes 100s of issues here's of the most significant bug that is caused by a similar thing: https://bugs.mojang.com/browse/MC-9568
