### ISSUE TITLE
[Bug]: Mod Dependency does not work for 1.20.4

### ISSUE THREAD

**Issue by 3Monika4** [ThatGravyBoat/Duckling#36]
### Bug Description

I'm trying to load this mod which seems to work with both Forge and NeoForge. However when I try to launch, it crashes. I look at the log and see that I need the dependency, recourcefullib. I download resourcefullib forge version, it still crashes and says Im missing the dependency. So I download the one it's specifically requesting, that being resourcefullib-neoforge-1.20.4-2.4.6.jar Despite me playing on Regular forge and not NeoForge (which the duckling mod supports both)
This dependency file allows the game to load, but then tells me that the file that mod specifically is requesting is not a valid mod file (probably because it's a neoforge file) and it will not accept anything else. It currently seems that playing with this mod on 1.20.4 is not possible without some kind of fix.

### How to Reproduce?

1. Download resourcefullib-neoforge-1.20.4-2.4.6.jar 
2. Download Duckling for 1.20.4 Forge/Neoforge version
3. Put them in mods folder
4. Says the mod is not a proper mod file

1. Download any other version of resourcefulib for forge
2. Launch the game
3. Crash on launch
4. Look at logs, error stems from dependency

### Expected Behavior

It's expected to launch and not crash upon putting the right file in

### Version

4.0.0

### Mod Loader Version

1.20.4 - Forge 49.0.50

### Mod Loader

Forge

### Logs or additional context

[latest.log](https://github.com/ThatGravyBoat/Duckling/files/15445620/latest.log)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Download a newer version of resourceful lib

**Comment by ThatGravyBoat** [comment]
The error you're getting is because forge and neoforge use different library versions

**Comment by 3Monika4** [comment]
> Download a newer version of resourceful lib

As I stated in the post, I had already tried the newest forge version and it will simply crash and logs tells me that the dependency is missing, even though it is present

**Comment by 3Monika4** [comment]
> The error you're getting is because forge and neoforge use different library versions

I understand that, which is why it's confusing that the mod refuses to load unless its with a mod that uses a different library

Edit: My main issue here is that the game is requesting for the neoforge version specifically in the log when I'm using regular forge and regular forge resourcefullib of any version is ignored
