### ISSUE TITLE
[Feature Request]: Duck Meat

### ISSUE THREAD

**Issue by SafeOfArsenal** [ThatGravyBoat/Duckling#4]
### Is your feature request related to a problem?

no

### Solution(s)

When the entity is killed it will drop raw duck

### Describe alternatives you've considered

or have it drop raw chicken

### Mod Version

1.0.3

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
We will likely never add duck meat because we don't want people to be killing ducks.
