### ISSUE TITLE
[Bug]: V4.0.0 Doesnt work on Forge 1.20.1

### ISSUE THREAD

**Issue by AqueleHaru** [ThatGravyBoat/Duckling#40]
### Bug Description

Instant crash when trying to open.

### Version

4.0.0

### Mod Loader Version

1.20.1-47.3.10

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/7Ze5aQr

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
we do not support forge anymore.
