### ISSUE TITLE
[Bug]:  Ducks sounds aren't dynamic, they play at the constant volume no matter the distance

### ISSUE THREAD

**Issue by BugmanBugman** [ThatGravyBoat/Duckling#5]
### Bug Description

Title. You will hear the duck sounds by your player character constantly despite being far waya

### How to Reproduce?

1. go by ducks
2.  be far away
3. notice how you can still hear them

### Expected Behavior

duck sounds to lower by distance

### Version

1.0.3

### Mod Loader Version

1.18.2 latest

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Fixed in the latest release.
