### ISSUE TITLE
[Bug]: Ducking mod prevents spawning of other mobs

### ISSUE THREAD

**Issue by hadrus** [ThatGravyBoat/Duckling#6]
### Bug Description

Duckling mod messing with spawning of other mobs. They just dont spawn.

Affected mobs:
1. Vanilla Minecraft:
- Dolphins
- Squids

2. Alex mobs:
- Cachalote Whales
- Giant Squids
- Hammerhead Shark
- Mimicube
- Mantis Shrimp
- Frilled Shark
- Mimic Octopus

### Version

1.0.4

### Mod Loader Version

1.18.2 - 40.1.0

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Where did you find out that Duckling did this because all I do with spawning is set the ducks and quacklings spawns to Rivers and Swamps respectively and that's it.

**Comment by ThatGravyBoat** [comment]
And as dolphins dont spawn in either it makes no sense that it "stops" them from spawning

**Comment by hadrus** [comment]
Ikr. But it is what it is. Maybe some incompatibilities with other mods.

**Comment by hadrus** [comment]
> Where did you find out that Duckling did this because all I do with spawning is set the ducks and quacklings spawns to Rivers and Swamps respectively and that's it.

Tested with and without it.

**Comment by hadrus** [comment]
Mods that i use in pack:
[modlist.zip](https://github.com/ThatGravyBoat/Duckling/files/8696342/modlist.zip)

Bug appears after I add Duckling.
