### ISSUE TITLE
[Bug]: holiday_fruit_cake.png got invisible pixels on it

### ISSUE THREAD

**Issue by PinkGoosik** [ThatGravyBoat/Duckling#7]
### Bug Description

Those pixels makes texture looking weird in-game

### How to Reproduce?

1. See item in-game

### Expected Behavior

texture shouldnt have those pixels

### Version

1.0.5

### Mod Loader Version

0.14.6

### Mod Loader

Fabric

**Comment by Theoness1** [comment]
yes!
