### ISSUE TITLE
[Bug]: Breeding doesn't work in the latest All of Fabric 5 with ducks, neither do they react to wheat seeds

### ISSUE THREAD

**Issue by heyjudek** [ThatGravyBoat/Duckling#8]
### Bug Description

As the title says, one cannot use wheat seeds on ducks. But using an empty hand to right click on them makes a heart appear around them but nothing else happnes.

### Version

1.0.5

### Mod Loader Version

0.14.6

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Ducks breed with bread not wheat seeds

**Comment by heyjudek** [comment]
My bad, I assumed it would be wheat seeds since they were following me in creative mode when I had wheat seeds. It is cleared up then :)
